version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:8001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
      - node
      
  laravel:
    build:
      context: ./laravel
    expose:
      - "8000"
    depends_on:
      - mysql

  node:
    build:
      context: ./node
    expose:
      - "9000"
    depends_on:
      - mongo

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Nilz@123
      MYSQL_DATABASE: fsbzgmdb
      MYSQL_USER: fasbiz
      MYSQL_PASSWORD: f6a3ZgM9y
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
